Repository cloudfoundry/terraform-provider-cloudfoundry, pull requests merged in 2025-08, with the labels that each got.

#276 chore: update Terraform test matrix
  .github/workflows/test.yml
Labels: ignore-for-release, internal

#277 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#279 docs: add information for import and drift detection
  docs/index.md
  docs/resources/service_instance.md
  guides/DRIFTDETECTION.md
  guides/IMPORT.md
  templates/index.md.tmpl
  templates/resources/service_instance.md.tmpl
Labels: documentation

#283 chore(deps): Update Go version to 1.25
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  go.mod
Labels: dependencies, go
