Repository cloudfoundry/terraform-provider-cloudfoundry, pull requests merged in 2025-04, with the labels that each got.

#176 Lint action update
  .github/workflows/test-opentofu.yml
  .github/workflows/test.yml
  .golangci.bck.yml
  .golangci.yml
  internal/mta/api_default.go
  internal/mta/client.go
  internal/provider/datasource_service_instance.go
  internal/provider/utils_test.go
Labels: ignore-for-release

#179 feat: add module as parameter for mta resource
  docs/resources/mta.md
  internal/provider/datasource_mtas_test.go
  internal/provider/resource_mta.go
  internal/provider/resource_mta_test.go
  internal/provider/types_mta.go
Labels: enhancement

#188 fix : inconsistent plan for private docker app image
  internal/provider/types_app.go
Labels: bug

#185 fix : route destination issue with app
  docs/resources/route.md
  internal/provider/resource_route.go
Labels: bug

#183 feat: Added deploy logs for mta in TF_LOG
  docs/resources/mta.md
  internal/mta/util.go
  internal/provider/resource_mta.go
Labels: enhancement

#191 fix : make spaces in security group computed so that overwrites dont happen
  internal/provider/fixtures/resource_security_group_crud.yaml
  internal/provider/fixtures/resource_security_group_invalid_name.yaml
  internal/provider/fixtures/resource_security_group_invalid_rule.yaml
  internal/provider/resource_security_group.go
  internal/provider/resource_security_group_test.go
  internal/provider/types_security_group.go
Labels: bug

#192 chore : v1.5.0 Prep Work
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
Labels: ignore-for-release
